# Site settings
title: Thomas Wicker
email: design@thomaswicker.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my online blog, resume and personal site for ramblings about my life. 
baseurl: "http://thomaswicker.com" # http://thomaswicker.com/test
author: "Thomas Wicker"
url: "http://thomaswicker.com" # the base hostname & protocol for your site
twitter_username: thomasjwicker
github_username:  thomaswicker

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - AIs
  - components
  - node_modules
  - pdfs
  - PSDs
  - gulpfile.js
  - .gitignore
  - .sass-cache
  - .sublime-project
  - gulpfile2.js
